# Generated by Django 5.1.3 on 2024-11-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookService', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='book',
            field=models.ManyToManyField(related_name='book', to='BookService.book'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Mystery', 'Mystery'), ('Science', 'Science'), ('Fantasy', 'Fantasy'), ('Biography', 'Biography'), ('Romance', 'Romance'), ('Children', 'Children')], max_length=200),
        ),
    ]
